config/routes.rb
AnItCom::Application.routes.draw do

  match 'projects' => 'projects#index'
  get "projects/BSB_OPAC_plus"
  get "projects/RUBopac_mobil"
  get "projects/Stadtbibliothek_Bremen_OPAC_mobil"

  get "projects/VTA"

  match 'kontakt' => 'pages#kontakt'
  match 'projekte' => 'pages#projects'
  match 'html5-test' => 'pages#html5_test'
  match 'websites' => 'pages#websites'
  match 'impressum' => 'pages#impressum'
  root :to => "pages#home"

  match 'vortraege' => 'vortrag#index'
  get 'vortrag/mobile_opacs_bayerische_opacs_immer_und_ueberall'
  get 'vortrag/der_mobile_opac_der_bayerischen_staatsbibliothek'
  get 'vortrag/mobile_opacs_perspektiven_und_chancen'
  get 'vortrag/web_20_social_network_services'
  get 'vortrag/web_20_in_bibliotheken'
  get 'vortrag/soziale_netzwerke_bezirksjugendwerk_der_awo_westliches_westfalen'
  get 'vortrag/scala_workshop_bayerische_staatsbibliothek'
  get 'vortrag/soziale_netzwerke_effektiv_nutzen_am_beispiel_von_facebook_twitter_und_google'
  get 'vortrag/scala_workshop_smarchive_edition'
  get 'vortrag/scala_workshop_smarchive_beginner'
  get 'vortrag/scala_parallel_collections'
  get 'vortrag/youtrack_talk'
  get 'vortrag/scala_monads_and_stackable_traits'
  get 'vortrag/introduction_to_scala_clueda'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  
end

app/controllers/pages_controller.rb
#coding: utf-8
class PagesController < ApplicationController

  def home
      @page_title = "Home"
  end
  
  def kontakt
      @page_title = "Kontakt"
  end
  
  def vortraege
      @page_title = "Vorträge"
  end
  
  def projekte
      @page_title = "Projekte"
  end
  
  def webseiten
      @page_title = "Webseiten"
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def BSB_OPAC_plus
  end

  def RUBopac_mobil
  end

  def Stadtbibliothek_Bremen_OPAC_mobil
  end

  def VTA
  end

end

app/controllers/vortrag_controller.rb
#coding: utf-8
class VortragController < ApplicationController
  def index
    @title="Vorträge"
  end

  def der_mobile_opac_der_bayerischen_staatsbibliothek
  end

  def mobile_opacs_bayerische_opacs_immer_und_ueberall
  end

  def mobile_opacs_perspektiven_und_chancen
  end

  def web_20_social_network_services
  end

  def web_20_in_bibliotheken
  end

  def soziale_netzwerke_bezirksjugendwerk_der_awo_westliches_westfalen
  end

  def scala_workshop_bayerische_staatsbibliothek
  end

  def soziale_netzwerke_effektiv_nutzen_am_beispiel_von_facebook_twitter_und_google
  end

  def scala_workshop_smarchive_edition
  end

  def scala_monads_and_stackable_traits
  end

  def introduction_to_scala_clueda
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def page_title
        if @page_title.nil? then
            ""
        else
            " | #{@page_title}"
        end
    end
    
    def meta_tags
    end
    
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/vortrag_helper.rb
module VortragHelper
end

app/views/layouts/_footer.html.haml
%footer{:id => "page_footer"}
	%nav
		%ul
			%li=link_to 'Home', root_path
			%li=link_to 'Kontakt', kontakt_path
			%li=link_to 'Impressum', impressum_path
	%section{:id => "cr"}
		&copy; Andreas Neumann, AN-iT 2011
	%section{:id => "adresse"}
		#org
			AN-iT
		#adr
			#street-address Wagerstraße 10
			%div
				%span{:class =>'postal-code'} 85635
				%span{:class =>'locality'} Höhenkirchen-Siegertsbrunn
			#country-name Deutschland
	.clear

app/views/layouts/_head.html.haml
%head
	%title 
		AN-iT.com
		=page_title
	= stylesheet_link_tag :all
	= javascript_include_tag :defaults
	<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->
	<link type="text/css" rel="stylesheet" media="only screen and (max-device-width: 481px)"  href="mobile_stylesheets/mobile.css" />
	<meta name="viewport"  content="initial-scale=1"/>

app/views/layouts/_header.html.haml
%header{:id => "page_header"}
	=link_to image_tag("AN-iT-Logo.png", :size => '200x101'), root_path
	%nav
		%ul
			%li=link_to 'Home', root_path
			%li=link_to 'Vorträge', vortraege_path
			%li=link_to 'Websites', websites_path
			%li=link_to 'Projekte', projects_path
			%li=link_to 'Kontakt',  kontakt_path
			%li=link_to 'Impressum',  impressum_path
	#mobile_button Navigation
	:javascript
		$(document).ready(function(){
			mobile_navigation();
			}
		);
		
		function mobile_navigation() {
			$("#mobile_button").click(function() {
				$("#page_header nav").slideToggle();
			})
		}

app/views/layouts/application.html.haml
!!! 5
%html
	=render 'layouts/head'
	%body
		%section{:id => 'page'}
			=render 'layouts/header'
			%section{:id => "main_section"}
				=yield
				%div{:class => "cleaner"}
				=render :partial=>'shared/like'
				
			=render 'layouts/footer'

app/views/pages/home.html.haml
%h1 Andreas Neuman IT - AN-iT
%article
	%header
		%h2 Andreas Neumann M.A.
		=image_tag 'Andreas-Neumann-small.png' ,{:id => 'andreas-neumann'}
		%ul
			%li Beratung / Consulting
			%li Schulungen und Vorträge zum Thema mobile Development, Webdesign und Programmierung
			%li Anwendungsentwicklung mit Scala, Java oder Ruby
			%li Konzeption, Design, Hosting und Durchführung von Webauftritten
		%p
			mehr zu meiner Person finden Sie unter:
			=link_to 'www.neumann.biz', 'http://www.neumann.biz/cv', :rel => 'nofollow'
%article
	%header
		%h2 Schwerpunkte
	%ul
		%li Webentwicklung : HTML 5, CSS 3, jQuery, Ruby on Rails 3, Sinatra, Lift
		%li Microservices und verteilte System: Akka, REST		
		%li Suchmaschinentechnik
		%li Berabeitung und Präsentation von OCR-Dokumenten
		%li Semantische Analyse und Datenextraktion aus Texten

%article
	%header
		%h2 Verfügbarkeit
	%p Bis auf weiteres bin ich leider völlig ausgelastet und kann keine weiteren Projekte mehr annehmen.

app/views/pages/html5_test.html.haml
%fieldset
	%legend HTML 5 Formular
	%p
		%label text
		%input{:type => 'text' , :placeholder => 'etwas Text'}
	%p
		%label email
		%input{:type => 'email', :placeholder => 'mail@exaple.com'}
	%p
		%label url
		%input{:type => 'url', :placeholder => 'http://www.an-it.com'}
	%p
		%label tel
		%input{:type => 'tel', :placeholder => '+49891234567'}
	%p
		%label date
		%input{:type => 'date'}
	%p
		%label color
		%input{:type => 'color'}

app/views/pages/impressum.html.erb
<section id='impressum'>
<h1>Impressum</h1>
<article>
<h2>Angaben gemäß § 5 TMG:</h2>
<ul>
	Andreas Neumann<br/>
	IT-Dienstleitungen<br/>
	Wagerstraße 10<br/>
	85635 Höhenkirchen<br/>
	<%=link_to "Kontakt", kontakt_path %>
</ul>


</article>

<article>
<p>Quelle: <i>Impressumgenerator <a href="http://www.e-recht24.de" target="_blank">von e-Recht24.de</a></i></p>
</article>
<article>
<h2>Haftungsausschluss:</h2>
<p><strong>Haftung für Inhalte</strong></p>
    <p>Die Inhalte unserer Seiten wurden mit größter Sorgfalt erstellt. 
      Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte 
      können wir jedoch keine Gewähr übernehmen. Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für 
      eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. 
      Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht 
      verpflichtet, übermittelte oder gespeicherte fremde Informationen zu 
      überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige 
      Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der 
      Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon 
      unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem 
      Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei 
      Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte 
      umgehend entfernen.</p>
    <p><strong>Haftung für Links</strong></p>
    <p>Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren 
      Inhalte wir keinen Einfluss haben. Deshalb können wir für diese 
      fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte 
      der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der 
      Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung 
      auf mögliche Rechtsverstöße überprüft. Rechtswidrige 
      Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente 
      inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte 
      einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen 
      werden wir derartige Links umgehend entfernen.</p>
    <p><strong>Urheberrecht</strong></p>
    <p>Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten 
      unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und 
      jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen 
      der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads 
      und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen 
      Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, 
      werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche 
      gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. 
      Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.</p>
    <p><strong>Datenschutz</strong></p>
    <p>Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf unseren Seiten personenbezogene Daten (beispielsweise Name, 
      Anschrift oder eMail-Adressen) erhoben werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben.   
    </p>
    <p>Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. 
      bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. 
      Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht 
      möglich. </p>
    <p>Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten 
      durch Dritte zur Übersendung von nicht ausdrücklich angeforderter 
      Werbung und Informationsmaterialien wird hiermit ausdrücklich widersprochen. 
      Die Betreiber der Seiten behalten sich ausdrücklich rechtliche Schritte 
      im Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails, 
      vor.</p><p> </p>
<p><strong>Datenschutzerklärung für die Nutzung von Facebook-Plugins
		 (Like-Button)</strong></p>
		 <p>Auf unseren Seiten sind Plugins des sozialen Netzwerks Facebook,
		 1601 South California Avenue, Palo Alto, CA 94304, USA integriert.
		 Die Facebook-Plugins erkennen Sie an dem Facebook-Logo oder
		 dem "Like-Button" ("Gefällt mir") auf unserer Seite. Eine Übersicht
		 über die Facebook-Plugins finden Sie hier:
		 <a href="http://developers.facebook.com/docs/plugins/" 
		 target="_blank">http://developers.facebook.com/docs/plugins/</a>.<br />
		 Wenn Sie unsere Seiten
		 besuchen, wird über das Plugin eine direkte Verbindung zwischen Ihrem
		 Browser und dem Facebook-Server hergestellt. Facebook erhält dadurch
		 die Information, dass Sie mit Ihrer IP-Adresse unsere Seite
		 besucht haben. Wenn Sie den Facebook "Like-Button" anklicken während
		 Sie in Ihrem Facebook-Account eingeloggt sind, können Sie die Inhalte
		 unserer Seiten auf Ihrem Facebook-Profil verlinken. Dadurch kann
		 Facebook den Besuch unserer Seiten Ihrem Benutzerkonto zuordnen. Wir
		 weisen darauf hin, dass wir als Anbieter der Seiten keine Kenntnis vom
		 Inhalt der übermittelten Daten sowie deren Nutzung durch Facebook
		 erhalten. Weitere Informationen hierzu finden Sie in der
		 Datenschutzerklärung von facebook unter
		 <a href="http://de-de.facebook.com/policy.php" target="_blank">
		 http://de-de.facebook.com/policy.php</a></p>
     <p>Wenn Sie nicht wünschen, dass Facebook den Besuch unserer Seiten Ihrem 
     Facebook-Nutzerkonto zuordnen kann, loggen Sie sich bitte aus Ihrem
     Facebook-Benutzerkonto aus.</p><p> </p>
<p><strong>Datenschutzerklärung für die Nutzung von Google Analytics</strong></p>
		 <p>Diese Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. 
     ("Google"). Google Analytics verwendet sog. "Cookies", 
     Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse 
     der Benutzung der Website durch Sie ermöglicht. Die durch den Cookie erzeugten 
     Informationen über Ihre Benutzung dieser Website (einschließlich Ihrer 
     IP-Adresse) wird an einen Server von Google in den USA übertragen und 
     dort gespeichert.</p>
     <p>Google wird diese Informationen benutzen, um Ihre Nutzung der Website 
     auszuwerten, um Reports über die Websiteaktivitäten für die Websitebetreiber 
     zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung 
     verbundene Dienstleistungen zu erbringen. Auch wird Google diese Informationen 
     gegebenenfalls an Dritte übertragen, sofern dies gesetzlich vorgeschrieben ist 
     oder soweit Dritte diese Daten im Auftrag von Google verarbeiten. Google wird 
     in keinem Fall Ihre IP-Adresse mit anderen Daten der Google Inc. in Verbindung 
     bringen.</p>
     <p>Sie können die Speicherung der Cookies durch eine entsprechende Einstellung 
     Ihrer Browser-Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in 
     diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website vollumfänglich 
     werden nutzen können. Sie können darüber hinaus die Erfassung der durch das 
     Cookie erzeugten und auf Ihre Nutzung der Website bezogenen Daten (inkl. 
     Ihrer IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google 
     verhindern, indem sie das unter dem folgenden Link verfügbare Browser-Plugin 
     herunterladen und installieren: <a href="http://tools.google.com/dlpage/gaoptout?hl=de">http://tools.google.com/dlpage/gaoptout?hl=de</a>.<p> </p>
<p><strong>Datenschutzerklärung für die Nutzung von Google +1</strong></p>
		 <p><i>Erfassung und Weitergabe von Informationen:</i><br />
     Mithilfe der Google +1-Schaltfläche können Sie Informationen weltweit
     veröffentlichen. über die Google +1-Schaltfläche erhalten Sie und andere
     Nutzer personalisierte Inhalte von Google und unseren Partnern. Google
     speichert sowohl die Information, dass Sie für einen Inhalt +1 gegeben
     haben, als auch Informationen über die Seite, die Sie beim Klicken auf
     +1 angesehen haben. Ihre +1 können als Hinweise zusammen mit Ihrem
     Profilnamen und Ihrem Foto in Google-Diensten, wie etwa in
     Suchergebnissen oder in Ihrem Google-Profil, oder an anderen Stellen auf
     Websites und Anzeigen im Internet eingeblendet werden.<br />
     Google zeichnet Informationen über Ihre +1-Aktivitäten auf, um die 
     Google-Dienste für Sie und andere zu verbessern. Um die Google 
     +1-Schaltfläche verwenden zu können, benötigen Sie ein weltweit 
     sichtbares, öffentliches Google-Profil, das zumindest den für das 
     Profil gewählten Namen enthalten muss. Dieser Name wird in allen 
     Google-Diensten verwendet. In manchen Fällen kann dieser Name auch 
     einen anderen Namen ersetzen, den Sie beim Teilen von Inhalten über 
     Ihr Google-Konto verwendet haben. Die Identität Ihres Google-Profils 
     kann Nutzern angezeigt werden, die Ihre E-Mail-Adresse kennen oder 
     über andere identifizierende Informationen von Ihnen verfügen.<br />
     <br />
     <i>Verwendung der erfassten Informationen:</i><br />
     Neben den oben erläuterten Verwendungszwecken werden die von Ihnen 
     bereitgestellten Informationen gemäß den geltenden 
     Google-Datenschutzbestimmungen genutzt. Google veröffentlicht 
     möglicherweise zusammengefasste Statistiken über die +1-Aktivitäten 
     der Nutzer bzw. gibt diese an Nutzer und Partner weiter, wie etwa
     Publisher, Inserenten oder verbundene Websites. </p><p> </p>
<p><strong>Datenschutzerklärung für die Nutzung von Twitter</strong></p>
		 <p>Auf unseren Seiten sind Funktionen des Dienstes Twitter eingebunden.
		 Diese Funktionen werden angeboten durch die Twitter Inc., 795
		 Folsom St., Suite 600, San Francisco, CA 94107, USA. Durch das Benutzen
		 von Twitter und der Funktion "Re-Tweet" werden die von Ihnen
		 besuchten Webseiten mit Ihrem Twitter-Account verknüpft und anderen
		 Nutzern bekannt gegeben. Dabei werden auch Daten an Twitter übertragen.</p>
     <p>Wir weisen darauf hin, dass wir als Anbieter der Seiten keine
     Kenntnis vom Inhalt der übermittelten Daten sowie deren Nutzung durch
     Twitter erhalten. Weitere Informationen hierzu finden Sie in der
     Datenschutzerklärung von Twitter unter
     <a href="http://twitter.com/privacy" target="_blank">http://twitter.com/privacy</a>.</p>
     <p>Ihre Datenschutzeinstellungen bei Twitter können Sie in den
     Konto-Einstellungen unter
     <a href="http://twitter.com/account/settings" target="_blank">http://twitter.com/account/settings</a> ändern.</p>
<p> </p>
<p><i>Quellverweis: <a href="http://www.e-recht24.de/muster-disclaimer.htm" target="_blank">Disclaimer</a> von eRecht24, dem Portal zum Internetrecht von Rechtsanwalt Sören Siebert, <a href="http://www.e-recht24.de/artikel/datenschutz/6590-facebook-like-button-datenschutz-disclaimer.html" target="_blank">Facebook Disclaimer von eRecht24</a>, <a href="http://www.google.com/intl/de_ALL/analytics/tos.html" target="_blank">Datenschutzerklärung Google Analytics</a>, <a href="http://www.google.com/intl/de/+/policy/+1button.html" target="_blank">Datenschutzerklärung für Google +1</a>, <a href="http://twitter.com/privacy" target="_blank">Datenschutzerklärung für Twitter</a></i></p>
</article>
</section>

app/views/pages/kontakt.html.haml
%h1 Kontakt
%article
	%header 
		%h2 Anschrift
	#hcard-Andreas-Neumann{:class =>'vcard'}
		.fn Andreas Neumann
		#org AN-iT
		.adr
			.street-adress Wagerstraße 10
			%div
				%span{:class =>'postal-code'} 85635
				%span{:class =>'locality'} Höhenkirchen-Siegertsbrunn
			.contry-name Deutschland
%article
	%header
		%h2 Web
	%section
		%p
			%strong Github
			%a{ 'href' => 'http://github.com/daandi'}
				https://github.com/daandi
		%p
			%strong Twitter
			%a{ 'href' => 'http://twitter.com/andreas_neumann'}
				andreas_neumann
			
%article
	%header
		%h2 Telefon und Email
	%section
		%p
			%strong Tel.:
			%a{ 'href' => 'tel:+49-176-811-43664'}
				+49 176 811 43664
		%p
			%strong Email:
			=mail_to 'info@an-it.com'
		
%article
	%header
		%h2 Anfahrt
	=render 'shared/google_maps'	

app/views/pages/websites.html.haml
%h1 Websites
%p Von AN-iT entworfene Websites; ein kleiner Überblick.
%article
	%header
		%h2 PTN-GmbH
	%p 
		Die PTN-GmbH ist ein mittelständisches Unternehmen, welches im Bereich Außenwerbung tätig ist.
		Der Wunsch war eine pflegeneutrale und unaufwändige Webpräsenz.
		AN-iT hat eine Image-Seite konzipiert und diese ins Netz gebracht.
	%p=link_to 'PTN-GmbH', 'http://www.ptn-gmbh.org', :rel => 'nofollow'
	%p=image_tag 'websites/PTN-GmbH.png'

app/views/projects/BSB_OPAC_plus.html.haml
%header
	%h1 
		=link_to 'OPACplus mobil', 'http://opacplus.bsb-muenchen.de', :rel => 'nofollow'
		der
		=link_to 'Bayerischen Staatsbibliothek', 'http://www.bsb-muenchen.de', :rel => 'nofollow'
%section
	=image_tag 'opac-plus-mobile.png' , :class => 'projectPicture'
	%aside
		%br 
			Der OPACplus mobil ist eine offizielle
			=link_to 'Apple Web Application', 'http://www.apple.com/webapps/searchtools/bayerischestaatsbibliothekopacplusmobil.html', :rel => 'nofollow'
	%p Unter Beibehaltung der bestehenden Infrastruktur und mit einem wartungsneutralem Plugin wird die OPAC-Software dahingehend optimiert, dass eine speziell für Smartphones zugeschnittene Ansicht erzeugt wird. 
	%p Das Plugin basiert auf CSS und Javascript-Techniken und unterstützt Apple iPhone, Apple iPad, alle Android-Smartphones, Opera Mobile, Opera Mini und den Internet Explorer Mobile.

app/views/projects/RUBopac_mobil.html.haml
%header
	%h2
		Ruhr-Universität Bochum:
		=link_to 'RUBopac mobil', 'http://opac.ub.ruhr-uni-bochum.de/', :rel => 'nofollow'
	%section
		=image_tag 'ub-bochum-mobile.png', :class => 'projectPicture'
		%p Beratung bei der Einrichtung der mobilen Version des RUBopac. 

app/views/projects/Stadtbibliothek_Bremen_OPAC_mobil.html.haml
%header
	%h1
		Stadbibliothek Bremen: 
		=link_to 'OPAC mobil', 'http://opac.stadtbibliothek.bremen.de/webOPACClient/start.do', :rel => 'nofollow'
%section
	=image_tag'stadtbibliothek-bremen-mobil.png', :class => 'projectPicture'
	%p Beratung bei der Einrichtung mobilen Version des OPACs der Stadtbibliothek Bremen. 
	%p Erstellen und Design der Grafiken für die iPhone-Web-App.

app/views/projects/VTA.html.haml
%header
	%h1 Volltxtsuche auf OCR-Texten mit Ergebnispräsentation auf Originaldokumenten
%section
	%p
		Das Projekt umfasst mehrere Komponenten zur Suche und Anzeige von im OCR-Orozess gewonnen Daten.
	%article
		%h2 Anzeigekomponente
		%p
			Die Anzeigekomponente erlaubt synchrone Anzeige auf dem graphischen Abbild des Dokuments und in der reinen Textrepräsentation.
			Sowhohl eine spätere Abänderung der Suche, wie acuh Highlighting sind möglich.
			Die beiden Komponenten lassen sich auch problemlos getrennt einsetzen.
			Die oberfläche ist hochflexibel, erlaubt den Wechesel von graphischer zu symbolischer (textueller) Repräsentation des Dokuments.
			Die Umsetzung benötig keine Zusatzsoftware und ist in jedem Handelsüblichen Browser lauffähig.
	
	%article
		%h2 Suchkomponente
		%p
			Erlaubt das Suchen im Volltext eines mit OCR bearbeiteten Dokuments.
			Die flexible Suchkomponente lässt sich mit verschiedenn verbreitetn Suchmaschinen, wie z.B. FAST oder Lucene betreiben und erlaubt auch eine konföderierte Suche über mehre Quellen / Indices / Suchmaschinen hinweg.
	%article
		%h2 Einsatz
		%p=image_tag 'VTA2.png' , :class => 'projectPicture'
		%p	
			Die Volltxtsuche auf OCR-Texten mit Ergebnispräsentation auf Originaldokumenten findet unter anderem Einsatz auf
			%ul
				%li
					%p=link_to "Chronicon : historicum.net ","http://www.historicum.net/home/", :rel => "nofollow"
					%p=link_to "Beispiel", "https://www.historicum.net/metaopac/search?View=hist&q=bsb10376791&db=15&View=hist&q=&q=K%C3%B6nig%20Ludwig%20I&showFulltextPage=115", :rel => "nofollow"
				%li
					%p=link_to "VIFA MUSIK : Virtuellen Fachbibliothek Musikwissenschaft","https://www.vifamusik.de/", :rel => "nofollow"
					%p=link_to "Beispiel", "http://www.vifamusik.de/search?q=bsb10527398&db=17&View=mus&q=kadenz&showFulltextPage=169", :rel => "nofollow"
		
	

app/views/projects/index.html.haml
%h1 
	Projekte
%article
	%header
		%h2 Volltextsuche und Präsentation
	%ul
		%li=link_to "Bayerische Staatsbibliothek:Volltxtsuche auf OCR-Texten mit Ergebnispräsentation auf Originaldokumenten","/projects/VTA"
%article
	%header
		%h2 Mobile Development
	%ul
		%li=link_to "Bayerische Staatsbibliothek: OPAC plus mobil","/projects/BSB_OPAC_plus"
		%li=link_to "Stadtbibliothek Bremen: OPAC mobil","/projects/Stadtbibliothek_Bremen_OPAC_mobil"
		%li=link_to "Ruhr-Universität Bochum: OPAC der OPAC - Ruhr-Universität Bochum","/projects/RUBopac_mobil"

app/views/shared/_download_file.html.haml
=link_to(image_tag('pdf_icon.png') + file.gsub(/.*\//,"") + ' herunterladen', file)